Repository akrck02/kinokoro, pull requests merged in 2024-08, with the labels that each got.

#13 Feature camera fix
  export_presets.cfg
  nodes/camera/camera.gd
  resources/fonts/PIXELADE.TTF.import
  resources/sounds/base_lo_fi.wav
  resources/sounds/base_lo_fi.wav.import
  scenes/park.tscn
Labels: enhancement, camera

#24 Feelings, start screen, house and tweaks
  icon.svg
  materials/outline_shader_material.tres
  materials/tilemap.tres
  nodes/camera/camera.gd
  nodes/chat_bubble/chat_bubble.gd
  nodes/chat_bubble/chat_bubble.tscn
  nodes/npc/cattotem.gd
  nodes/npc/cattotem.tscn
  nodes/npc/turtle.gd
  nodes/pet/pet.gd
  nodes/pet/pet.tscn
  nodes/ui/ui.tscn
  project.godot
  resources/sounds/icon.svg
  resources/sounds/icon.svg.import
  resources/sprites/effects/shadow.png
  resources/sprites/effects/shadow.png.import
  resources/sprites/food.png
  resources/sprites/homeWireframe.png
  resources/sprites/landscape.png
  resources/sprites/tiles/home.png
  resources/sprites/tiles/home.png.import
  resources/sprites/tiles/house.png
  resources/sprites/tiles/house.png.import
  resources/sprites/tiles/landscape.png
  resources/sprites/tiles/landscape.png.import
  resources/sprites/tiles/wireframe.png
  resources/sprites/tiles/wireframe.png.import
  scenes/home.gd
  scenes/home.tscn
  scenes/house.gd
  scenes/house.tscn
  scenes/main.gd
  scenes/main.tscn
  scenes/park.tscn
  shared/canvas.gd
  shared/classes/game_sprite.gd
  shared/classes/spritesheet.gd
  shared/constants.gd
  shared/managers/game_sprites.gd
  shared/managers/scene_manager.gd
Labels: bug, camera, pet, settings

#27 Feature settings
  .gitignore
  materials/button_hover.tres
  materials/button_normal.tres
  materials/button_pressed.tres
  nodes/pet/pet.gd
  nodes/ui/settings.gd
  nodes/ui/settings.tscn
  resources/sprites/icons/pet-outlined.png
  resources/sprites/icons/pet-outlined.png.import
  resources/sprites/icons/pet.png
  resources/sprites/icons/pet.png.import
  resources/theme.tres
  shared/managers/settings_manager.gd
Labels: enhancement

#28 Feature compressimages
  bin/compresor/imageCompresor.py
  default_bus_layout.tres
  scenes/minigolf.tscn
  scenes/park.tscn
Labels: enhancement

#45 drag and drop system, touch input events rework, better tilemap extended adapted to godot 4.3 ...
  nodes/camera/camera.gd
  nodes/grid_area/grid_area.gd
  nodes/grid_area/grid_area.tscn
  nodes/house/house.gd
  nodes/house/house.tscn
  nodes/pet/pet.gd
  nodes/pet/pet.tscn
  nodes/tilemap/tilemap_extended.gd
  nodes/ui/settings.gd
  nodes/ui/ui.gd
  nodes/ui/ui.tscn
  project.godot
  resources/sprites/Pasted image.png.import
  resources/sprites/tamnquin2.png.import
  resources/sprites/tiles/home.png
  resources/sprites/tiles/landscape.png
  resources/theme.tres
  scenes/house.gd
  scenes/main.gd
  scenes/park.tscn
  shared/classes/game_sprite.gd
  shared/classes/input_data.gd
  shared/classes/spritesheet.gd
  shared/constants/constants.gd
  shared/constants/context.gd
  shared/constants/input_type.gd
  shared/managers/game_sprites_manager.gd
  shared/managers/save_manager.gd
  shared/managers/scene_manager.gd
  shared/managers/touch_input_manager.gd
  shared/node_extensor.gd
  shared/signal_database.gd
  shared/utils/positions.gd
Labels: enhancement
